
  name: ckan
  version: '1.24.0'
  summary: KSP automated mods installer
  description: |
    The Comprehensive Kerbal Archive Network is a repository of metadata about mods 
    for Kerbal Space Program, and associated tools to work with this metadata.

  grade: stable
  confinement: strict

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
